# Generated by Django 4.0.4 on 2022-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Укажите уникальный адрес для страницы задачи. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', unique=True, verbose_name='Адрес для страницы c категорией')),
                ('description', models.TextField(help_text='Опишите категорию', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите текст поста', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, help_text='Добавьте изображение к посту', null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
