# Generated by Django 4.0.4 on 2022-12-29 13:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Опубликовать или оставить в черновике?', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(help_text='Введите текст поста', verbose_name='Текст'),
        ),
    ]
