# Generated by Django 4.0.4 on 2022-12-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/User.png', help_text='Добавьте изображение к профилю', null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='Фото профиля'),
        ),
    ]
